# This is a basic workflow to help you get started with Actions

name: DocFX Build and Publish

# Controls when the action will run. 
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-doc:
    runs-on: ubuntu-latest
    name: DocFX Build and Publish
    steps:
    - uses: actions/checkout@v1
    # ...
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docs/docfx.json

    - name: Publish
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
